### ISSUE TITLE
OAuth Error: TraktAuthorizationException: Unauthorized - OAuth must be provided

### ISSUE THREAD

**Issue by scottkuhl** [henrikfroehling/TraktApiSharp#104]
Trakt API Sharp Version: 0.11.0

When trying to access resources in the Trakt API that require OAuth authentication I am getting the following error:

TraktApiSharp.Exceptions.TraktAuthorizationException: Unauthorized - OAuth must be provided

   at TraktApiSharp.Requests.Base.TraktRequest'3.<ErrorHandlingAsync>d__71.MoveNext() in C:\projects\traktapisharp\Source\Lib\TraktApiSharp\Requests\Base\TraktRequest.cs:line 368
   at TraktApiSharp.Requests.Base.TraktRequest'3.<QueryAsync>d__8.MoveNext() in C:\projects\traktapisharp\Source\Lib\TraktApiSharp\Requests\Base\TraktRequest.cs:line 50
   at TraktApiSharp.Modules.TraktBaseModule.<QueryAsync>d__4`2.MoveNext() in C:\projects\traktapisharp\Source\Lib\TraktApiSharp\Modules\TraktBaseModule.cs:line 0
   at TraktApiSharp.Modules.TraktUsersModule.<GetCustomListsAsync>d__11.MoveNext() in C:\projects\traktapisharp\Source\Lib\TraktApiSharp\Modules\TraktUsersModule.cs:line 335
   at Conduktor.Controllers.HomeController.<Index>d__2.MoveNext() in C:\Users\scott\source\repos\Conduktor\Conduktor\Controllers\HomeController.cs:line 58

Here is the code in a ASP.NET Core 2.0 Controller that can produce it:

```cs
public async Task<IActionResult> Index(string code = "")
{
    var client = new TraktClient(ClientId, ClientSecret);
    var authorization = new TraktAuthorization();

    if (code != string.Empty)
    {
        authorization = await client.OAuth.GetAuthorizationAsync(code);
        Response.Cookies.Append("AccessToken", authorization.AccessToken);
        Response.Cookies.Append("RefreshToken", authorization.RefreshToken);
    }
    else
    {
        var authFound = Request.Cookies.TryGetValue("AccessToken", out var accessToken);
        var refreshFound = Request.Cookies.TryGetValue("RefreshToken", out var refreshToken);

        if (!authFound || !refreshFound)
        {
            ViewBag.AuthorizationUrl = client.OAuth.CreateAuthorizationUrl();
            return View();
        }
        else
        {
            var revoked = await client.Authentication.CheckIfAccessTokenWasRevokedOrIsNotValidAsync(accessToken);

            if (revoked)
            {
                authorization = await client.DeviceAuth.RefreshAuthorizationAsync();
                Response.Cookies.Append("AccessToken", authorization.AccessToken);
                Response.Cookies.Append("RefreshToken", authorization.RefreshToken);
            }
            else
            {
                client = new TraktClient(ClientId, ClientSecret)
                {
                    Authorization = TraktAuthorization.CreateWith(accessToken, refreshToken)
                };
            }
        }
    }

    var lists = await client.Users.GetCustomListsAsync("me");
    return View();
}
```

**Comment by henrikfroehling** [comment]
@scottkuhl 
The reason for the exception is that the request itself has an optional OAuth requirement and the library ignores this fact.

A workaround would be to set `client.Configuration.ForceAuthorization` to `true`.

**Comment by scottkuhl** [comment]
Thank you, I will give that a shot and see if it fixes it.

**Comment by scottkuhl** [comment]
That did the trick.  You can close the issue.  Thanks!
