### ISSUE TITLE
How to get Device authorization token

### ISSUE THREAD

**Issue by mwhisler** [henrikfroehling/TraktApiSharp#2]
I'm sure I'm just missing something here, but can you help me figure out why I'm getting this exception when I try to poll for authorization?

When I send the values through Postman, everything works just fine so I'm sure it's the way I'm using the TraktClient.  Here's my code:

`var client = new TraktClient("[id]", "[secret]");
var device = await client.DeviceAuth.GenerateDeviceAsync();
Console.WriteLine(device.UserCode); //go out and actually enter the code and complete the authorization
var token = await client.DeviceAuth.PollForAuthorizationAsync();`

I receive a TraktForbiddenException: Forbidden -invalid API key or unapproved app.  Thoughts?

**Comment by mwhisler** [comment]
I noticed that the Trakt.tv docs have the base URL as https://api.trakt.tv, but I see your default production URL is "https://api-v2launch.trakt.tv".

Also, check line 99 of TraktDeviceAuth.cs. Is it possible that the StringContent is changing the content type to text/plain instead of application/json?  If I change my HTTP calls to use text/plain I get the 403 status code.

**Comment by henrikfroehling** [comment]
> var client = new TraktClient("[id]", "[secret]"); var device = await client.DeviceAuth.GenerateDeviceAsync(); Console.WriteLine(device.UserCode); //go out and actually enter the code and complete the authorization var token = await client.DeviceAuth.PollForAuthorizationAsync();

Looks fine to me.
So, it seems, that the content type is missing for the request body. Thanks for the hint.

> I noticed that the Trakt.tv docs have the base URL as https://api.trakt.tv, but I see your default production URL is "https://api-v2launch.trakt.tv".

Yes, the base URL has been modified in the last week, I think. There was also, however, no announcement, at least I have not seen any. I only discovered this by accident.
The old URL works, though. But I will update the URL in the next release (the next bugfix release, but no later than next v0.2.0 release).

**Comment by henrikfroehling** [comment]
Should be fixed in the latest release: [TraktApiSharp 0.1.1](https://www.nuget.org/packages/TraktApiSharp/0.1.1)

**Comment by mwhisler** [comment]
Henrik, pulled down the latest version and all looks great! Thanks for handling that so quickly.  I'll be using this quite extensively so if I find anything else, I'll let you know.

**Comment by henrikfroehling** [comment]
I'm glad to hear that.
