### ISSUE TITLE
Search: Error converting value {null} to type 'System.Int32'. Path '[5].show.year'

### ISSUE THREAD

**Issue by nils703** [henrikfroehling/TraktApiSharp#3]
I'm using the following statement to search for shows:
`TraktPaginationListResult<TraktSearchResult> searchResults = await this.apiClient.Search.GetTextQueryResultsAsync(searchString, TraktApiSharp.Enums.TraktSearchResultType.Show);`

If i'm searching for "walking dead" it works fine. but if i only search for "walking" i get the following exception:
`An exception of type 'Newtonsoft.Json.JsonSerializationException' occurred in mscorlib.ni.dll but was not handled in user code
Additional information: Error converting value {null} to type 'System.Int32'. Path '[5].show.year', line 1, position 4757.`

**Comment by henrikfroehling** [comment]
The sixth (0 based index) result of that request (query == "walking") is the show "War Walks". But that show does not have a value for year. Year is null in this case and shouldn't be parsed by Json.
For the query == "walking dead", the sixth result is the show "Scare PewDiePie" and this show has a value for year and therefore does not throw an exception.
I'm working on a fix for this issue.

**Comment by henrikfroehling** [comment]
Should be fixed in the latest release: [TraktApiSharp 0.1.1](https://www.nuget.org/packages/TraktApiSharp/0.1.1)
