### ISSUE TITLE
It's not possible to get informations for "Special Seasons"

### ISSUE THREAD

**Issue by DanCooper** [henrikfroehling/TraktApiSharp#33]
Normaly all "Special Seasons / Seasons Specials" are handled as season = 0 (https://trakt.tv/shows/american-dad/seasons/0).

Your code throw an exeption if the season is 0:

`protected override void Validate()
        {
            base.Validate();

            if (Season <= 0)
                throw new ArgumentException("season must be a positive integer", "Season");

            if (Episode <= 0)
                throw new ArgumentException("episode must be a positive integer", "Episode");
        }`

**Comment by henrikfroehling** [comment]
There was a off-by-one error in the check for the season number. Will be fixed in Version 0.6.0.
