### ISSUE TITLE
Add missing "title" property in TraktSeason

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/TraktApiSharp#53]

**Comment by henrikfroehling** [comment]
It's not in the docs, but I noticed it in the return data of some requests in Postman.
The JSON property name is "title".

Feel free to ask any questions, if you're working on this issue.
And also thanks for working on it. :-)
My responses might take some time though, because I have some issues with my internet connection.

**Comment by henrikfroehling** [comment]
Please, also make sure to base your work off of the "dev"-branch, because this will be released in version 0.10.0 (currently tracked by branch "dev").

**Comment by Amoenus** [comment]
Noted. I will do that.
