### ISSUE TITLE
Add support for "users/hidden/{section}/remove" POST request

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/TraktApiSharp#55]
[API Reference](http://docs.trakt.apiary.io/#reference/users/hidden-items/remove-hidden-items)

**Comment by SR2k** [comment]
It seems like there's no `Title` property of `Objects.Get.Shows.Seasons.TraktSeason` class yet Trakt do send it within the JSON response. Or I just don't get it or someting...?

**Comment by henrikfroehling** [comment]
@SR2k Is already implemented. See issue #53 for more info. But it isn't released yet. Will be in version 0.10.0, which I'll release sometime during May.
