### ISSUE TITLE
Rename library / project / repository to "Trakt.NET"

### ISSUE THREAD

**Issue by henrikfroehling** [henrikfroehling/TraktApiSharp#58]
I'm thinking of renaming this project because the current name is quite long and not very catchy, in my opinion.

Candidates for a new name are: **Trakt.Net** or **TraktApi.Net**

**Comment by henrikfroehling** [comment]
The timeline for this would probably be somewhere around the release of the next major version 1.0.0 in May / June.

**Comment by henrikfroehling** [comment]
The best practice probably would be to create a new repository with the new name and reference the current repository as the previous and outdated one.

**Comment by henrikfroehling** [comment]
Just renaming the repository and the NuGet package might also be sufficient.

**Comment by henrikfroehling** [comment]
Final thought on this:
Rename this repository, leave the current NuGet package as it is and create a new NuGet package with the new name.

**Comment by henrikfroehling** [comment]
Poll for a new name: https://plus.google.com/+HenrikFröhling/posts/FmziX7kvNQV

**Comment by Amoenus** [comment]
I get 404 error.

**Comment by Amoenus** [comment]
Regarding the name change, I'd be tempted to rename this repository, add "formerly knows as ..." to readme (to aid search engines). In terms of name Trakt.Net seems more concise. Tags should be enough for search engines to find the right stuff.

**Comment by henrikfroehling** [comment]
@Amoenus Regarding the 404 error: You have to have a Google+ account and you have to be a member of the "Trakt.tv API" community on Google+. I updated my comment to make that more clear.

Regarding the renaming of the repository: I have to work out a little plan on how the renaming should go. But I will let you know as soon as I know more.

**Comment by henrikfroehling** [comment]
The following items are necessary in the following order:

- [ ] Change the global namespace "TraktApiSharp" to the new library name or its abbreviation
  - [ ] Create a separate commit for each subnamespace (e.g. one commit for "TraktApiSharp.Enums", one commit for "TraktApiSharp.Core", etc.)
- [ ] Rename Visual Studio project
  - [ ] Replace all occurrences of "TraktApiSharp" in Visual Studio project files (.csproj) / Rename project files
  - [ ] Replace all occurrences of "TraktApiSharp" in Visual Studio solution files (.sln) / Rename solution files
  - [ ] Replace all occurrences of "TraktApiSharp" in all build files (appveyor.yml)
  - [ ] Replace all occurrences of "TraktApiSharp" in NuGet files / Rename NuGet files
- [ ] Replace all occurrences of "TraktApiSharp" in all misc files (readme, license, contributing, coding_style)
- [ ] Update readme (Add some information message)
- [ ] Update website
- [ ] Rename repository

I will create an issue for each item.

**Comment by henrikfroehling** [comment]
The new library name will be **Trakt.NET**.

**Comment by henrikfroehling** [comment]
https://github.com/henrikfroehling/Trakt.NET/issues/3
